// src/js/components/NewLink.vue
<template xmlns:v-on="http://www.w3.org/1999/xhtml">
    <form class="new-link-form" v-on:submit.prevent="submitForm">
        <h2>
            New Link
        </h2>
        <label>
            Title
            <input type="text" name="title" v-model="title" lazy/>
        </label>
        <label>
            Description
            <input type="text" name="description" v-model="description" lazy/>
        </label>
        <label>
            URL
            <input type="text" name="url" v-model="url" lazy/>
        </label>
        <tag-list :tags="tags"></tag-list>
        <button type="submit">Submit</button>
    </form>
</template>

<script>
    var TagList = require('./TagList.vue');

    export default {
        components: {
            'tag-list': TagList
        },
        data: function () {
            return {
                title: undefined,
                description: undefined,
                url: undefined
            }
        },
        props: [
            'onSubmit',
            'tags'
        ],
        methods: {
            submitForm: function () {
                console.log(this.tags);
                this.onSubmit(this);
            }
        }
    }
</script>

// src/js/react/NewLink.jsx
'use strict';
// @flow

import React from 'react';
import binder from 'react-class-binder';
import {NEW_LINK_COMPONENT} from './component-constants';

export default class NewLink extends binder(React.Component) {
    titleInput: HTMLInputElement;
    descriptionInput: HTMLInputElement;
    urlInput: HTMLInputElement;
    
    submit(): void {
        console.log(this.titleInput.value);
        console.log(this.descriptionInput.value);
        console.log(this.urlInput.value);
    }

    inputRef(input: HTMLInputElement, name: string): void {
        let key = `${name}Input`;

        let self = this;
        self[key] = input;
    }

    isDisplayed(): boolean {
        return this.props.displayedComponent === NEW_LINK_COMPONENT;
    }

    render() {
        return (
            <form className={`new-link-form ${this.isDisplayed() ? '' : 'hidden'}`} onSubmit={this.submit}>
                <h2>
                    New Link
                </h2>
                <label>
                    Title
                    <input type="text" name="title" ref={(i) => this.inputRef(i, 'title')}/>
                </label>
                <label>
                    Description
                    <input type="text" name="description" ref={(i) => this.inputRef(i, 'description')}/>
                </label>
                <label>
                    URL
                    <input type="text" name="url" ref={(i) => this.inputRef(i, 'url')}/>
                </label>
                <button type="submit">Submit</button>
            </form>
        );
    }
}
